name: Rust

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install stable toolchain and other components
      uses: actions-rs/toolchain@v1.0.5
      with:
        profile: minimal
        components: rustfmt, clippy
    
    - name: format check
      run: |
        cargo fmt --manifest-path client/Cargo.toml -- --check
        cargo fmt --manifest-path substrate-api/Cargo.toml -- --check
        cargo fmt --manifest-path app/Cargo.toml -- --check
        cargo fmt --manifest-path enclave/Cargo.toml -- --check
    #TODO: enable this
    # - name: linter
    #   run: cargo clippy